/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pruebaconexionyimi;


public class Ventana1 extends javax.swing.JFrame {

    /**
     * Creates new form Ventana1
     */
    public Ventana1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        Titulo_Doctores = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        fondo = new javax.swing.JPanel();
        lateral = new javax.swing.JPanel();
        btn_Doctores = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        btn_Inicio = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btn_Pacientes = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        titulo = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btn_equis = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        btn_Inicio1 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        Panel_Inicio = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        jPanel18 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jPanel19 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel14 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        Titulo_Inicio = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        Titulo_Doctores.setBackground(new java.awt.Color(255, 255, 255));
        Titulo_Doctores.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Titulo_DoctoresMouseClicked(evt);
            }
        });
        Titulo_Doctores.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pruebaconexionyimi/Imagenes/icons8_infusion_pumps_40px.png"))); // NOI18N
        Titulo_Doctores.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 70, 50));

        jLabel36.setFont(new java.awt.Font("Cambria", 3, 36)); // NOI18N
        jLabel36.setText(" DOCTORES");
        Titulo_Doctores.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 190, 30));

        jLabel38.setBackground(new java.awt.Color(255, 255, 255));
        jLabel38.setFont(new java.awt.Font("Cambria", 3, 36)); // NOI18N
        jLabel38.setText("PACIENTES");

        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pruebaconexionyimi/Imagenes/icons8_hospital_bed_64px.png"))); // NOI18N
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fondo.setBackground(new java.awt.Color(255, 255, 255));
        fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lateral.setBackground(new java.awt.Color(0, 51, 102));
        lateral.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_Doctores.setBackground(new java.awt.Color(0, 51, 102));
        btn_Doctores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_DoctoresMouseClicked(evt);
            }
        });
        btn_Doctores.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pruebaconexionyimi/Imagenes/icons8_infusion_pumps_40px.png"))); // NOI18N
        btn_Doctores.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 80, 50));

        jLabel5.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("DOCTORES");
        btn_Doctores.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 110, 30));

        lateral.add(btn_Doctores, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 280, 50));

        jPanel4.setBackground(new java.awt.Color(0, 51, 102));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel4.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 37, -1, -1));
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Cambria", 3, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText(" HOSPITAL SANTOS");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 210, 70));

        jLabel3.setFont(new java.awt.Font("Cambria", 3, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("& AVALOS");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 120, 50));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pruebaconexionyimi/Imagenes/icons8_caduceus_40px.png"))); // NOI18N
        jPanel4.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 50, 60));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pruebaconexionyimi/Imagenes/icons8_caduceus_40px.png"))); // NOI18N
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, -1, 60));

        lateral.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 290, 110));

        jPanel5.setBackground(new java.awt.Color(0, 51, 102));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Cambria", 2, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("TEL: 449-458-4877");
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 120, 30));

        jLabel7.setFont(new java.awt.Font("Cambria", 2, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Correo:");
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 50, 20));

        jLabel19.setFont(new java.awt.Font("Cambria", 2, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("contacto@hospitalsaav.com");
        jPanel5.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 170, 30));

        lateral.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 510, 200, 90));

        jPanel13.setBackground(new java.awt.Color(0, 51, 102));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("CONTACTOS");
        jPanel13.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 120, 30));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pruebaconexionyimi/Imagenes/icons8_whatsapp_48px.png"))); // NOI18N
        jPanel13.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pruebaconexionyimi/Imagenes/icons8_email_50px.png"))); // NOI18N
        jPanel13.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 6, 50, 40));

        lateral.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 280, 50));

        btn_Inicio.setBackground(new java.awt.Color(153, 204, 255));
        btn_Inicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_InicioMouseClicked(evt);
            }
        });
        btn_Inicio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(255, 204, 204));
        jPanel8.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        btn_Inicio.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 37, -1, -1));
        btn_Inicio.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pruebaconexionyimi/Imagenes/icons8_hospital_3_48px.png"))); // NOI18N
        btn_Inicio.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 50));

        jLabel11.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("INICIO");
        btn_Inicio.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 120, 30));

        lateral.add(btn_Inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 280, -1));

        btn_Pacientes.setBackground(new java.awt.Color(0, 51, 102));
        btn_Pacientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_PacientesMouseClicked(evt);
            }
        });
        btn_Pacientes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pruebaconexionyimi/Imagenes/icons8_hospital_bed_64px.png"))); // NOI18N
        btn_Pacientes.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 50));

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("PACIENTES");
        btn_Pacientes.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 120, 30));

        lateral.add(btn_Pacientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 280, -1));

        fondo.add(lateral, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 340, 631));

        titulo.setBackground(new java.awt.Color(153, 204, 255));
        titulo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(153, 204, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel6.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 37, -1, -1));
        jPanel6.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        jLabel25.setFont(new java.awt.Font("Cambria", 3, 20)); // NOI18N
        jLabel25.setText(" HOSPITAL SANTOS");
        jPanel6.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 210, 70));

        jLabel26.setFont(new java.awt.Font("Cambria", 3, 20)); // NOI18N
        jLabel26.setText("& AVALOS");
        jPanel6.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 120, 50));

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pruebaconexionyimi/Imagenes/icons8_caduceus_40px.png"))); // NOI18N
        jPanel6.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 50, 60));

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pruebaconexionyimi/Imagenes/icons8_caduceus_40px.png"))); // NOI18N
        jPanel6.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, -1, 60));

        titulo.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 0, -1, -1));

        jPanel17.setBackground(new java.awt.Color(153, 204, 255));
        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setFont(new java.awt.Font("Cambria", 3, 16)); // NOI18N
        jLabel22.setText("ESPECIALISTAS EN EL ANÁLISIS DEL CORAZÓN");
        jPanel17.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 380, 60));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pruebaconexionyimi/Imagenes/icons8_stethoscope_100px.png"))); // NOI18N
        jPanel17.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 100, 90));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pruebaconexionyimi/Imagenes/icons8_heart_with_pulse_40px.png"))); // NOI18N
        jPanel17.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 30, 60, 50));

        titulo.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 580, 90));

        fondo.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, 1060, 140));

        btn_equis.setBackground(new java.awt.Color(255, 255, 255));
        btn_equis.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        btn_equis.setText("X");
        btn_equis.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_equis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_equisActionPerformed(evt);
            }
        });
        fondo.add(btn_equis, new org.netbeans.lib.awtextra.AbsoluteConstraints(1350, 0, 34, 40));

        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        fondo.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(372, 631, -1, -1));

        btn_Inicio1.setBackground(new java.awt.Color(0, 51, 102));
        btn_Inicio1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_Inicio1MouseClicked(evt);
            }
        });
        btn_Inicio1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel16.setBackground(new java.awt.Color(255, 204, 204));
        jPanel16.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        btn_Inicio1.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 37, -1, -1));
        btn_Inicio1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pruebaconexionyimi/Imagenes/icons8_hospital_3_48px.png"))); // NOI18N
        btn_Inicio1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 50));

        jLabel31.setFont(new java.awt.Font("Cambria", 1, 16)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("INICIO/HOME");
        btn_Inicio1.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 120, 30));

        fondo.add(btn_Inicio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 280, 50));

        Panel_Inicio.setBackground(new java.awt.Color(255, 255, 255));
        Panel_Inicio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel32.setBackground(new java.awt.Color(153, 204, 255));
        jLabel32.setFont(new java.awt.Font("Cambria", 3, 24)); // NOI18N
        jLabel32.setText("Misión");
        Panel_Inicio.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(475, 50, -1, 54));

        jLabel33.setBackground(new java.awt.Color(153, 204, 255));
        jLabel33.setFont(new java.awt.Font("Cambria", 3, 24)); // NOI18N
        jLabel33.setText("Visión");
        Panel_Inicio.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 50, -1, 54));

        jLabel34.setBackground(new java.awt.Color(153, 204, 255));
        jLabel34.setFont(new java.awt.Font("Cambria", 3, 24)); // NOI18N
        jLabel34.setText("Nosotros");
        Panel_Inicio.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(772, 50, -1, 54));

        jPanel12.setBackground(new java.awt.Color(153, 204, 255));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea4.setBackground(new java.awt.Color(153, 204, 255));
        jTextArea4.setColumns(20);
        jTextArea4.setFont(new java.awt.Font("Cambria", 2, 18)); // NOI18N
        jTextArea4.setRows(5);
        jTextArea4.setText(" Nosotros somo un grupo de \n estudiantes auxiliados por \n profesionales de diferentes áreas\n teniendo así una mayor capaci-\n dad de análisis y tener un uso de\n materiales, equipos médicos y \n herramientas para este análisis\n sea el adecuado para cada caso\n singular.");
        jTextArea4.setBorder(null);
        jScrollPane4.setViewportView(jTextArea4);

        jPanel12.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 290, 290));

        Panel_Inicio.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 100, 250, 330));

        jPanel18.setBackground(new java.awt.Color(153, 204, 255));
        jPanel18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea3.setBackground(new java.awt.Color(153, 204, 255));
        jTextArea3.setColumns(20);
        jTextArea3.setFont(new java.awt.Font("Cambria", 2, 18)); // NOI18N
        jTextArea3.setRows(5);
        jTextArea3.setText(" Nuestra misión es llegar a todo\n paciente que requiera un ECG\n y que este se sienta en total \n confianza sabiendo que su aná-\n lisis se le entregará al instante.\n También se espera movilizar la \n conciencia sobre el cuidado de \n uno de los órganos más impo-\n rtantes que tenemos, que es el \n corazón.\n ");
        jTextArea3.setBorder(null);
        jScrollPane3.setViewportView(jTextArea3);

        jPanel18.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 290, 290));

        Panel_Inicio.add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 100, 250, -1));

        jPanel19.setBackground(new java.awt.Color(153, 204, 255));
        jPanel19.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea2.setBackground(new java.awt.Color(153, 204, 255));
        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Cambria", 2, 18)); // NOI18N
        jTextArea2.setRows(5);
        jTextArea2.setText(" Nuestra visión es que el analisis\n del corazón sea una prioridad\n para todas las personas, por\n nuestra parte pondremos \n nuestros equipos médicos de \n análisis para que el paciente \n se vaya de la forma mas \n tranquila con datos y analisis\n certerteros que le brindaremos\n al momento de manera insta-\n nea, seguray confiable.");
        jTextArea2.setBorder(null);
        jScrollPane2.setViewportView(jTextArea2);

        jPanel19.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 290, 290));

        Panel_Inicio.add(jPanel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 250, 330));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pruebaconexionyimi/Imagenes/icons8_inspection_40px.png"))); // NOI18N
        Panel_Inicio.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, -1, 60));

        jLabel41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pruebaconexionyimi/Imagenes/icons8_conflict_30px.png"))); // NOI18N
        Panel_Inicio.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 60, 30, 40));

        jLabel42.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pruebaconexionyimi/Imagenes/icons8_meeting_room_50px.png"))); // NOI18N
        Panel_Inicio.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 50, 50, -1));

        fondo.add(Panel_Inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, 1060, 430));

        Titulo_Inicio.setBackground(new java.awt.Color(255, 255, 255));
        Titulo_Inicio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel10.setBackground(new java.awt.Color(255, 204, 204));
        jPanel10.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        Titulo_Inicio.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 37, -1, -1));
        Titulo_Inicio.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        jLabel39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pruebaconexionyimi/Imagenes/icons8_hospital_3_48px.png"))); // NOI18N
        Titulo_Inicio.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, 60));

        jLabel40.setFont(new java.awt.Font("Cambria", 3, 36)); // NOI18N
        jLabel40.setText("INICIO");
        Titulo_Inicio.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 220, -1));

        fondo.add(Titulo_Inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 310, -1));

        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 0, 1390, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_InicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_InicioMouseClicked
        Ventana1 v=new Ventana1();
        v.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_InicioMouseClicked

    private void btn_DoctoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_DoctoresMouseClicked
        Ventana2 v=new Ventana2();
        v.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_DoctoresMouseClicked

    private void btn_PacientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_PacientesMouseClicked
        Ventana3 v=new Ventana3();
        v.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_PacientesMouseClicked

    private void btn_equisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_equisActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btn_equisActionPerformed

    private void btn_Inicio1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Inicio1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_Inicio1MouseClicked

    private void Titulo_DoctoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Titulo_DoctoresMouseClicked
        
    }//GEN-LAST:event_Titulo_DoctoresMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel_Inicio;
    private javax.swing.JPanel Titulo_Doctores;
    private javax.swing.JPanel Titulo_Inicio;
    private javax.swing.JPanel btn_Doctores;
    private javax.swing.JPanel btn_Inicio;
    private javax.swing.JPanel btn_Inicio1;
    private javax.swing.JPanel btn_Pacientes;
    private javax.swing.JButton btn_equis;
    private javax.swing.JPanel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JPanel lateral;
    private javax.swing.JPanel titulo;
    // End of variables declaration//GEN-END:variables
}
